spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/kpimanage
      username: root
      password: root123
      maximum-pool-size: 30
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/local
      username: root
      password: root123
      maximum-pool-size: 30
      driver-class-name: com.mysql.jdbc.Driver